### ISSUE TITLE
Search term spell suggestion ignores URL parameters

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#443] opened 2013-10-09 17:51 UTC
When an improved spelling of a search term is suggested, the URL is assembled lazily, simply specifying `?q=[search term]`. If somebody follows this URL, they'll lose any other URL parameters that they've specified, such as the number of results to display per page. Assemble the URL properly.

**Comment by krues8dr** [comment] 2015-05-02 13:40
Moving this up in priority, since it's going to break things in the editions work and I didn't actually notice yet.

**Comment by krues8dr** [comment] 2015-05-07 15:49
We're going to need to append the editions query parameter here, too.  I'm going to reopen this for now since this is about to break as soon as I merge.  I'll back-port your changes and resolve after that.

**Comment by waldoj** [comment] 2015-05-07 15:50
My lazy fix was insufficient—shocking! ;)

**Comment by krues8dr** [comment] 2015-05-07 15:51
It's a great start, and does resolve this issue!  But I'm preemptively handling my regression. :)

**Comment by krues8dr** [comment] 2015-05-09 17:49
As predicted, c64093ce97453f2f55b04f99e03d0e4c6a5fd70f reopens this as a regression.  Working on that.

**Closed** 2015-05-12 01:39 UTC
Labels: Bug, Editions

**Comment by krues8dr** [comment] 2015-05-12 01:41
These three tickets ( #442 #442 #581) were really close in the code, and I was refactoring as I went, so it's all in one commit rather than discrete.  _shrug_  It works, though.
